apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpl-worker
  namespace: apps
spec:
  template:
    spec:
      containers:
        - name: fpl-worker
          env:
            - name: APP_ENV
              value: staging  # Set APP_ENV to 'staging'
