---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager
  namespace: network
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgAPEDgDLAyE18MGHId/1oqEz9qSg9dRVVjD54uNFo7DVhWbsdVK9NamexL57gNENgEIKY3byVX8+63zsMlp+QvONcJRts9ekiyQtlF+mg0vCfBnMwFYt14s/dtmcQ1YKBRHzLzsh2pcAcCQLYmYwrxmYNweCMkQXc4ZNRj0dzBBjPwpl4rIR3Zt0/Rl98Bt8uz5kdiJr5HMPhJb3adhy5fhYgR1rEiEyknc/gfRUFcLDj03KnBPphk39P37gb31Af40OVcP2LTZI68BP8s7bDz6mQUrecUmicb21vbGMh3qr/ayVcPUB1rL9jNN9qBjb65gDYXCKrRHesSSjlyjQuMfuM8R4ks9tU9LfcDhCXh79RFKLSIvJbiRUzzPPJaJ+SoKS5CE+mMX5dNzVfiMnoEtF7H9dKGcSse2T0LQcXcGmPdZzbj+lnvZJgym3u5cN/XAbAYBiMXLgE9vIugBQ3okNm3dROCVxGP7qPDP+R7qzSv2bJ0Uf7vXHLXBPWnedlmx2xCqnUjPlhp8fS96dJPQPsw4of/ztZPxMwMFDa/t4JLHJZXWNUkVLF210n6hnNInY6YZBjUZxk/g48FEuwcnpQv2KUS1Q/JbC7glgFb7lgpl8uINPGPl/brKjO5TKIP2MECx7u2snwvzYElHrKyPUenrBzy2TDx9D/ft2rO+2nk5lCXUmJCVjyc7Hd12hMkKrOTFCNC699H46AwdaciRo6rJhHPvgUgnrHud9yi6J1RFuo+VMpSW
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager
      namespace: network
