apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: reflector
    releaseName: reflector
    repo: https://emberstack.github.io/helm-charts
    version: 7.1.288
    namespace: kube-system
