apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: temporal
    version: 0.44.0
    releaseName: temporal
    repo: https://go.temporal.io/helm-charts
    valuesFile: values.yaml
    namespace: apps

#helmGlobals:
  #valuesFile: values.yaml