apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applicationsets
  namespace: ops
spec:
  project: applicationset-manager
  source:
    repoURL: https://github.com/verde-websites/fpl-infra.git
    targetRevision: main
    path: kubernetes/argocd/applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: ops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
