---
apiVersion: v1
kind: Secret
metadata:
  name: db-url
  namespace: production
stringData:
  databaseDsn: mysql+aiomysql://root:EMnSZaZbWnSJhgpfdxFyaqkvTbtRbOgo@autorack.proxy.rlwy.net:20650/railway

---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoid2FkZS1zYW0iLCJwYXNzd29yZCI6ImdocF9zcko0R0ljY3U1Q1RvQzVQZGpieGZwV0JEYzVTaTYza2xXNTkiLCJlbWFpbCI6InZlcmRlLXdlYnNpdGVzQGdtYWlsLmNvbSIsImF1dGgiOiJkMkZrWlMxellXMDZaMmh3WDNOeVNqUkhTV05qZFRWRFZHOUROVkJrYW1KNFpuQlhRa1JqTlZOcE5qTnJiRmMxT1E9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2024-10-09T20:29:20Z"
  name: github-registry-secret
  resourceVersion: "266757"
  uid: 55ed9f49-a61d-441d-a1a0-e46357e66a74
  namespace: production
type: kubernetes.io/dockerconfigjson
