---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-registry-secret
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgBWkgytsgXuxO9z3VpjQsb6GrH0oc1pEr7IvVfb0X7n5Neg0ZrPTouz14wL2c3JKMAt9KdMicK21jVELMdNp9XJ1LoqiQ5bZZk4oTo2qidmtKmTjx/+p0vZ6me4RbKWCvk7fRuwk6tYVuXcPg9DReHsfFs007WhIgULxhkWA/JqyLz8Te/3JxD7XUcwwasOJP+JYDbk94703uiXuW7kvp13ThU+iDQHseqOL1oHXhP2s1nMOS2Yp2fsHul17urvzBqdAOZvjjC691+FvVtjXBiKR0IMNlrTro/ipPlM57q+9Hj2x4xZGHx5o2ExRMPw2E5HDdWJAafTytw7oMP0iMJTOUhy00xnVrQPdYzE5pj18rK7lIPzs0vzuehoLL3+pLkrw++JdGbUeKZpU01ASwy70Z3N5Iy6T4wKwZ2zmY8yK+qaC0B/ocsYUrXt3tRcOQ9P28NUbl1xf5/eqQG6RMRI9Aen79Sub8KetNG+KSJJUbgedwP7akbKLAbiMMKd10IkUnUnyViUMdfoWuK+OJOBd3rknMl+etfCSfgECuN6mr3zzrJ5k+o1KYWfKMUxR2OhULI79hNWGhHyjCAzDolO+IiHMDMX9jtDg7neb2esQF5R3IKRpndGdbBkML9yAeyruf7Yp7haVX7bgfUXjrnW3Cp9UImO8didY7eqvN7fZtYaKzIdNy1RbGowUixc0eX/Voki5yCq1/Dmujef0m7z0lLXWcPbsDdlZ/gFHdd7bELoGc+qOn+S/qBycRbzkhe4BXeFCVkcG1HxlTYZCWeXdIbxusto2Ics25Lp/18zj05+QSFnP2tfyjN7oegiMtYiw05JHb5Z77wupCvV7o3qtAOerpBW5+GFLFNrrt/gTQSTr+bnP09n6JOopwcxIvntwDGTIgx5xEeNm/Ratvu7H+n+3pFn3SNvcut2tpcL6wzUpfjnn/0kgRF6Gh1D6x24Y/RF6tSsyjMZjF74AO8xrF5Rvg==
  template:
    metadata:
      creationTimestamp: null
      name: github-registry-secret
      namespace: staging
    type: kubernetes.io/dockerconfigjson
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-url
  namespace: staging
spec:
  encryptedData:
    databaseDsn: AgAl25hv3gTCRuDRY1ngiGSTuf6m9112eRwFRipVOyrqOONM7Lx0lk4c0QQp7Y8djAzgXTysadsNsHRXD42CbN3pO8w/2mx+blUxaLInsRssMaY4pzHhOrZQUVTDkQjXvWlAPliSZOiwGsih+t23N8Mg6uqUqpNo2LQf4Xi58rWs8MxOuqLQS90ffRsg4NAhOrdAcZhtGEtM2TLFkKLc5rrDluEO8B+UEI5tATlzU81S6qxB67tQMVZ7+uj6DHd08zSX7VuPevY5dWTgbkcOvBCPUIKG9mD+aAy5MdEA+HR7c702sdNqZHktG0JSjlsGCVQ2gcv+/xp3ZUTp1YfRMQzS4V1C7Xu6kBfwgZHnCcsYiATfAz1S7y5H+lyemOMtdPfCHhwFGedZV10UrzkuFMmKqBGpdXGjAF/jOZ03nBgV3pCU+L0VZYj4vnv0lXUqmbVCqVkiN7+yofJv48J6U10ZrnOljCxyktJBYbKSLSTttV/47SoUbVVWkmhDKGNZQZU1Zz8IAB7HctWOXAnt8NPulN0lucjuwY+gEX/KdKm9UBQxHLgKYIRB3i3sARMGuCLoQjP58hlmDn3I2tI6dItiv0vlQS/6lnZpOohTfpQyrFBJaFLHLB9SoC5k80TQoHpA8kongrpeForQr/+BN8c8j4bvnzJ596iTr/Goj5R4WcXyKbZR4wqW5oce7X/KipWe+lre91kEb0pAHxb8xFKNi2FbE8ZCULxalsG6VxoXV9C5oI4duc7YR6+wRRcveIM5bkBstmu2LcWgrSJEmVfCPfW1MrkCmyZTrb0rplxuG1c+p/hNU5ntBWkWPw==
  template:
    metadata:
      creationTimestamp: null
      name: db-url
      namespace: staging
