---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-url
  namespace: staging
spec:
  encryptedData:
    databaseDsn: AgAymUgIwaL9qx1sOaIN7ghwh9lA+taDbQV9NBs51PbD8vLdO+1pNGwGiOk96bXpAwOXImcDyVkU8O25dWLz1Uq6muQFziz8/gI8/J9++ySFqM/bwRau6Z9IWEWlNGPV4jSAjzEe2cLZ920WNf60AcApph8ttWS09dH9OfP4PzIYC7YC7I+KUFqvqGFjL7OoOMYGFxP54hegosAEaLa5PyJhA+EI8+Q/y5mdCohzeHSFfHYlEzMheIZDmhGmhrRHlIM47Ot0ZiJ0P3NuCih6dxCG0ca28otUG9JCqpdISWdF4/qtbB6oPSeynkYflTDn0f4NhKnP+vC2IbEVV8z+Qj9Uursfl5hh7HrVQb91QP3e6tBXzCm+8txhq0zFR2XevNbcg7tmPtDsHYb2CNe2TcYSk2OC4UGvEYYpe9oAT99V0wbiT5HpXmU38e7lAvc43SShn9fbOuiH/481qzy7JjwlZxFT3nxOQ+8Oe+EHYddk7BrrHBB79Mbl8CyhHFYsF1ethfdswigcDRM7oFpv6maRbl1mBYTEvn+18OYkkojmLSBXruX6KsZvkUX93ZU1ry6hgqd9dzi5P/VgcuB5yYijlNdHjNW4Ak37zVl87q4XXVjB8zqD7HKBlSRAEEUH36LUewVNfdIL1mUKA4+AM65s0wovYHkohnG9cCl9mRdUfVd+/dInRB3z0ZLTQpD8IwfsehKqxVywX0HuQpvaXL/E7Mte5e3L1BlUoUi5tYSeSyJftp7FgZHkqi2DERwxipyIaAosR7QHpy4gv8mVkcpXPifya8bYbqyxptKAPA03YNY1h+3zJVd6xZBCjg==
  template:
    metadata:
      creationTimestamp: null
      name: db-url
      namespace: staging
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-registry-secret
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgBWRV/5MB/3sk7BKLwi4MCOf5NOrr+sJidbDb2v1lyeKH7RC8xjMu4En90/UwwuAhtyxll1BFTb5V7eOBi0TnOkmm2odnabdkNf9KuYATIcf4Com74KcefsX3kyW/bH0uK3hI4cTxmOh7FBJtSuQW52nCMK/T0G0AgJYgHtXjRhNoKvwXQPIJX329MhO0jbEO/kNrDwzLokjrntsv/t6gI5xRY0sMMHEuPZcm2+Lv8DCUp0w5DZKdSh9G+v0c/IJU6Pi7z7mwND7sSynpItSNLvg6+zc0G+GMRKm75JC6vQ5+DYl7/1g1RfkuT3cYEr+z54hzvF4QN+2Nx7fGjDBJeccbxPCi4pWmsE7oEvtz8Fm4S1p5ND0Rl/rEZwStOq3zffpDiYA3ES4aeJ12wvChyDD2jlA/VssTtsCoC2QI8egG6r/7lP5dGOBI0agmougpdAKP3efTCzfE7avqju9Jd1y9iLTouu8w8m6EtKCnkI8PQYbG/pQoBc+/MBudgbKmKV0XnbrVRUkvrHPen9IQ8fzq+BqBzJnyPnaVrSn7/tSWOvRXa5lG2xaGTWRjMBSmECbWFcAOhhju+d4yQXjSlHGyfrg3aTimh+F9iNeC430s1rCq0nmr4u2IgAZaRlay6o3AtuwbCevdpp2mVE78ID97bJg7m8FO58P/ZaRLxnFmxGXhogSHn2j4JgyDLheEW6EShtWSKP2KNOAfs/kDKTR0f4k51sS1VUi0SLOWPOmQVbe76gSvBBa0rJTCEePf/+0Cg1gH+Y4MBgBj05Cobwu/oAQXL9ncDsa3IHeSSkE3edeRC0D3Or/fJa0YN/SkylswOdk4GRL8DQfdQ//aF6SQAb/9vmVga/x+8UpnAmp4ByLkx1Vihr8De7YXBLwi/mzodERYVwr7/e1O/y9A4UzDRzBdcX/ZBCGh5nrCG9VOTgs0KPUFpbpK28DMD91K9kqZVeSkIWrWSwVJxa3Kckx2XW2g==
  template:
    metadata:
      creationTimestamp: null
      name: github-registry-secret
      namespace: staging
    type: kubernetes.io/dockerconfigjson
