apiVersion: apps/v1
kind: Deployment
metadata:
  name: agency
  namespace: external
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agency
  template:
    metadata:
      labels:
        app: agency
    spec:
      containers:
        - name: agency-application
          image: ghcr.io/atlanticsites/agency:latest
          ports:
            - name: web
              containerPort: 3000
      imagePullSecrets:
        - name: ghcr-creds
