---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-url
  namespace: dev
spec:
  encryptedData:
    databaseDsn: AgAz281NqrEd9FwDidABRWw0RwjsirkT844r8fSysbuu8fFy1/1zbzGm+nQ2z5gFYloI1vapJUHQU3QAPSOyT0bWRvp2kC1HdrurX4h7ab+pmvaYHZkCos9TQWcLFyt+gJ/vSyzEtU9P7VV0CCzd+p+9peVp//5bm3gfdqaALJhRZ6yiWzJovEqeQ548WO9odWvKWjy3/voS7qoO45wIyxGuWYSFFOZ5BgIFNK9BNqT3HV9kS6iIO91pks1RTLzMhDoSxiJGh6binno/YYSYAGvoXqG33sD7z6mTdcDOvN/oAjBoosc3J2hdRgnZapm01XSyv6VmaPeHKhwMYsomzaqZWO0lU/pdb4VHvFh3W6zTxokxCV6TCuqO3HPVu0lrEG6rLsSEylvALRHwAbS/joSw4IzWoum/MJypS3u4yJZX58h2NAtuiIhi9MaoRCG2Bq5ijuUmHe+SRJr/Z7gQvG4czHQ9wZ6O2XgkAfmN/LdISfPxbE8Xpt8aqDqdfO3AOysZ+l8yMIlZH7vK8ApeGDr/8caSj+AS2picSZw1jYcZCzGUQjSfBRxIWCd8U+jOStqahtyHQJQ3p+5sWCRMHhTjTblutlJ5e/UbZQX1S6dd/nfuLelIi6+S28rR2ZIwVFvPcooFhQMpIdBvjsnH0vIhBZDCqrFgHYVGbzIcfn05dXUwHfNiNkjY3dzzOC4MC+QFoSLh9s0L89H9Fh5OuAY09D5pO/It+tSULhEqAGeuoG7KEhy4vzYhI+sGs12zO8kF/HaoI1gZCiAA74v4//UWeZhJl51blkLECrFYeSCkVaPyasj1jBucHKsS/g==
  template:
    metadata:
      creationTimestamp: null
      name: db-url
      namespace: dev
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-registry-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgB5TCVkGXHTJrMaSgXOGeNYWsZs3AcJMOBERwWXi6R+HGey1PvnA1GWKYPj0lEEuBCUbOMY8QnoXrRoct2HuMbKstZAN9eT1OW5yDCbWb8TB9dLGbi6etNHL+5cN68yGSfz81TZFpc9yone0RLzydoLeE0FwF6zecXmmuoZ/5EhcUpmyMaTnSG098trSCN7wJpYhzUPbq/tTGWQUT68CNuHDBwgLGN9dwXDR/EqP8cBduVzxMQaciwMcyvHQLIh4JyLGhr8ELNyJQLW7qikLhuZLZzFRQQacunQ2y9Ltz8mv9+qxTtBLEgyfE4KzhrRCnxj/aCWdztu/3O/qPgSFq1W/N2l70KOpb1wMk9Jgr+zcd2PkaOmg9B7RHNnp5+ppDsMPgdIqjpY9jqY59KvrMo0kP5iLx7/9XiNYL8lK47Juh7frPwmyoHbQKc/8X7TQSj/W7R6a1NVZF3Dn52YSZyuzA+PqsFJMzj9kcmY83mo3C3EKY6vmwNHJeHUB69JiE1m5qaBsAymXMX70T32qbeUpw3r036VCaoOY6EbzuBrijJawRZBzA4l1+yso+ghBOhO6xymWKfwVDy6VM3w0Vv9/pm9BqK7NvscMzjs2M8hwXs4faowvNrvENe8SXPqlZJBqu306ocBlcmUf2UGLxdRTI/gmQ7kfhziJsDPIolI4T4qlERMtU3JAnDwmx6RA62dbguR5KufjoTt9FmHK3JW20KQafJ4fhyr/Iz7PQcAjVbdXh2JMOVLfsrBoMILrPLMVBNt0edup38e//S9bgBGXFuGnJtzLswwn2yPqV/e39NQaBONCx//oae6E5D9zdqH3NLhlwsdHDVfZL1ZjB2dmhPx41jSmcQzVyJE0/mnRP9XXPDMKlyFvQkGXTFHq0YHOg/SIJt+cS5Dtl6Mx5QlZP6+JF2y1+49ZnVQ/md8FimRaMahSAl/0Fz+Euy0IqLL1s8zQVbh2511b4MOgCDBX6JToA==
  template:
    metadata:
      creationTimestamp: null
      name: github-registry-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
