apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#resources:
#  - ../../base

helmCharts:
- repo: https://kubernetes.github.io/ingress-nginx
  name: ingress-nginx
  version: 4.11.2
  releaseName: nginx-private
  valuesFile: values.yaml
  namespace: network

#helmGlobals:
#  valuesFile: values.yaml