---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager
  namespace: network
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgBva9eQdwuhexE2+LQyR+iRzwY0dxisRm7watVWYkFpD2ugQByqCmZvHEwbytOoE0UltYcyoGOLHpQ0rFEX36T3GjNutktFCpD/GI3lAiL31FGF/LaG0Nf6r4nZ+VG8uDyDFGqHQup45PWakWCsGLpcu694R9ckbNzMmDCRdCCJDupP7bd6q/soSlqixmxcipgsTsjbFMjf0nqd5tUddJboFnUNcx+P2Xa34U55Li5nO2Ob+Ce/l6EJc6IcYpWh/kF6OumwoqYZbx5u6qJm30tEQUozZBUE7SS1w7Zbt7oUJWw1EwFTE2wca4/vuJDTupHuZK7Xd5fcU9rDL9n02D7J5/eZaiaPFymNPRHHYQqPhST9ILaLVf22PtR/HLj4OKyc/N1YmZxkWz2SxmbBMU9OF1NPMbyvK47GiD0O6kVV3bF9U+jXtAij1Y0n44tsBTZLPFI8lE+8YKV0J5bOHaWoH+Ya06PxpymELEu+ZVtQ5WUiCVqw/URzmmsgxdnSlk6TicPdM0fVfbZ5rXW9TPjFDrb6QZX+EZwUwbjLqLWCFuXkBhWVH8uKveonebrakaH+UVEVHplIDdBvRUzsP4RXRgYdwopRoA7EVsExOOQV0ymtQZZVmhnwWhzEQwC+l4L+NM2rwcqT42Fa3I4fmwZbTPywtvbihka92KSrUO7LhM87PAAFX/Sgj0J5nFbtwHON3IElc9qz6WrL11+O3N3LaogJKRB9G/y0i8wIL1R5IGn4TOWjWAzr
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager
      namespace: network
    type: kubernetes.io/dockerconfigjson
---
