apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ops

resources:
  - ../../base

helmCharts:
  - name: argocd-apps
    version: 2.0.0
    releaseName: argocd-apps
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yaml
    namespace: ops
#    
#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization
#
#resources:
#  - ../../base
#
#helmGlobals:
#  valuesFile: values.yaml