apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- sealed-secrets.yaml
namespace: production
patchesStrategicMerge:
- patch-deployment.yaml
- patch-ingress.yaml
images:
- name: ghcr.io/verde-websites/fpl-infra/myfpl-api
  newTag: production-f880551
