apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
  - namespace.yaml

helmCharts:
  - name: ingress-nginx
    releaseName: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.11.2
    namespace: ingress-nginx
    valuesInline:
      controller:
          watchIngressWithoutClass: true
          config:
            "use-forwarded-headers": true
            "compute-full-forwarded-for": true
            "use-proxy-protocol": false
