apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: myfpl-api-staging
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      myfpl-api=ghcr.io/verde-websites/myfpl-api/myfpl-api
    argocd-image-updater.argoproj.io/myfpl-api.update-strategy: "digest"
    argocd-image-updater.argoproj.io/myfpl-api.tag: "regex:^staging-([a-f0-9]{7})$"

resources:
- ../../base
- sealed-secrets.yaml

namespace: staging

images:
- name: ghcr.io/verde-websites/myfpl-api
  newTag: placeholder

patchesStrategicMerge:
- patch-deployment.yaml
- patch-ingress.yaml
