apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- sealed-secrets.yaml

namespace: staging

images:
- name: ghcr.io/verde-websites/myfpl-api
  newTag: placeholder

patchesStrategicMerge:
- patch-deployment.yaml
- patch-ingress.yaml
