apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- sealed-secrets.yaml
namespace: staging
patchesStrategicMerge:
- patch-deployment.yaml
- patch-ingress.yaml
images:
- name: ghcr.io/verde-websites/fpl-infra/myfpl-api
  newTag: staging-7e16ee5
