---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-url
  namespace: staging
spec:
  encryptedData:
    databaseDsn: AgAxcjnIOdrmRf8YtLoN5qe8H/0k1+wJ/wc3eTD+pXMGOOrakqnt8dWkeJp12E5bv+z5keu8YCaHxbdzK75Uby6gPsgr8XoOYmnN2aRdFsYnunHu/et69rpNY9vjebL2uT2e/0QnJ2aZMZoxoEf11IrvabYSYNVxZDxG6aboRs2wm8pjvdV6sNlseRO74r0sOwvmA/LbnjA5jv+9efHQMug26aQ25HAj76Ej+hnEIrtC6u5D92QnIgQHvRK4yKibrj5DHcTDtlebUjgLTkp4bskKeCtq8jy9zhxPkXtrsLobqaCo1QB3edvPfJsjJqMZxxiPuNvt5zW/CY2AWFZEo+jdduNK/0vp1HGzqpkjRh6TIDgbrzpaEcRbNPqGjrUJhrK5z7dpJUl+0cf7SmnW331fN29Dxrn2wWqnACbKNBdHTVpygqiw+I7YqHsG7qunSsSPYF684wNe3O8S6MpFtnD9LVMd1JAySu3NUfxul9RFAMQ7OWYYoNnC/ufEOozPFNu3IGgOJNnuqV19jYS/3RQzV67k2oGMw/INz+4VI0wyr0acShugcIPa6xgg2w6ZcpPXtmRSmwSa7Ue49wqdBC8pOM6pR/LzZWscpujWxw88Dfg6g4v4K2H1LPKX0R+zGlfLs9QMcBKaLv6lwTYHHFCWlONrYGa/jKcGpNfg9qjAMrsFX5Yp7Uq0EoNFPy1OVQomfnS/TtNw9oVgpJRluMKqN6drpfZQ9zrfpazH+iK8WW8LuXOBlh29CQKV9XvOG9dkOTEHLX5CExei7Ivmv6pOuyvUDz7E0j2W5PSd2XctJYGWpO8uGKVzZ9yxsQ==
  template:
    metadata:
      creationTimestamp: null
      name: db-url
      namespace: staging
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-registry-secret
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgBGjl8Z4RmaxZ8R2D5hCbmYehdaSJKLW0UNrmrY8e9W6ta/+iMzb1NW5O8cokEA4e3+QztmLLLqYUKvL3eM3vuevDDkKwvzifo/ljG0KUhy9THHu+YdRz1qrJJ2xt6+CTNosySSdsm3fQTGzk0588/PSyiIx+4JXrXYFUUs+OP2Ai9UpJOGEjjCKRUOCVDpfjl8CwGRZe2Zs43Iw9JFHFB9XoKo36BJLnhwnrhv4VDH4ojN/EzS12RKW/8A3SYxvuK9nO243LwFQ44XB+Fm+2TifYGFbgM4jZ5qu6SP6eGwoWsbeHuEAWqMameaK+udi4Oq3qi5y41pb3Wwzj+C9YmcG8uaHuUkHd2D1TiMimuOPmUBrIf/J3Ik/aQmmoqeUTKMlDPx+NIllSX+KeP3oIhy+P6XLhms0lvgNNT7sW6Jr2HyyJ1SbMfUw0r2vP8WhaPrMKhw2+Zh6tHIWb8lLwMB6Bnp0f4VKCv5wxSjVPZuRtNVE9tVdkYZvH0Q5cB5gLxWLcpZgC6m8+7z4RLdc7sehtXKVzVPaaKpHJSU9vJCNQKi4NuNM6eq0XHiCzvWCIknrdaGAif9lPblYxItH1eXi+GdXOHrU1cQjA3C+qXwtn0TWbzZeINSzwhTBwx0fb+dGotTfVKYN2ihwHqdHHO/e72lN7zjeBGIR0wWni69shpWNMSO4q790T7lhcGND2AjmFyUXlUnqrD4dBhbuaKqbrCPsur8ll1865woGKrw0nbDpzUUtS7Tiuwc6+Le59g+6Q4+ePOFOvstgXyaYKDSKXLwbMrP23smaaWmMwNB5N9DYUVeyvA8MozHsxBVoFu9g/LjFvVg7+sSfHt1V3W9H2/QvEoL+ycAJyKH0npkoh5paf3C5BV0bj5abhPpN/WriWb/QNVcKzHLjZc8CApjjdHYos9mCc8EmZzQtjOmsW4Ho9yz8iwiY3IOZb0pUFs4WVhLv5xleM/zqikaPgR9EkNSZw==
  template:
    metadata:
      creationTimestamp: null
      name: github-registry-secret
      namespace: staging
    type: kubernetes.io/dockerconfigjson
