applicationsets:
  apps:
    name: apps
    goTemplate: true
    goTemplateOptions: ["missingkey=error"]
    generators:
      - git:
          repoURL: https://github.com/verde-websites/fpl-infra.git
          revision: HEAD
          directories:
            #- path: "kubernetes/apps/*/overlays/dev"
            - path: "kubernetes/apps/*/overlays/staging"
            #- path: "kubernetes/apps/*/overlays/production"
    template:
      metadata:
        name: "{{index .path.segments 2}}-{{index .path.segments 4}}" # App name and environment
        annotations:
          argocd-image-updater.argoproj.io/image-list: |
            {{index .path.segments 2}}=ghcr.io/verde-websites/{{index .path.segments 2}}/{{index .path.segments 2}}
          argocd-image-updater.argoproj.io/{{index .path.segments 2}}.update-strategy: |
            {{if eq (index .path.segments 4) "staging"}}latest{{else}}tag{{end}}
          argocd-image-updater.argoproj.io/{{index .path.segments 2}}.tag: |
            {{if eq (index .path.segments 4) "staging"}}latest{{else}}regex:^([a-f0-9]{7})${{end}}
      spec:
        project: default
        source:
          repoURL: https://github.com/verde-websites/fpl-infra.git
          targetRevision: main
          #targetRevision: |
            #{{if eq (index .path.segments 4) "staging"}}main{{else}}{{index .path.segments 4}}{{end}}
          path: "{{.path.path}}"
          kustomize:
            namespace: "{{index .path.segments 4}}" # Dynamically set namespace
        destination:
          server: https://kubernetes.default.svc
          namespace: "{{index .path.segments 4}}" # Namespace (dev, staging, production)
        syncPolicy:
          automated:
            selfHeal: true
            prune: true
          syncOptions:
            - CreateNamespace=true
            - FailOnSharedResource=true