apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/clusterissuer.yaml
  - resources/sealed-secrets.yaml

helmCharts:
  - repo: https://charts.jetstack.io
    name: cert-manager
    version: v1.15.3
    includeCRDs: true
    releaseName: cert-manager
    valuesFile: values.yaml
    namespace: network
