apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: myfpl-api-dev
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      myfpl-api=ghcr.io/verde-websites/myfpl-api/myfpl-api
    argocd-image-updater.argoproj.io/myfpl-api.update-strategy: "latest"
    argocd-image-updater.argoproj.io/myfpl-api.tag: "regex:^latest$"
resources:
- ../../base
- sealed-secrets.yaml

namespace: dev

images:
- name: ghcr.io/verde-websites/myfpl-api
  newTag: latest

patchesStrategicMerge:
- patch-deployment.yaml
- patch-ingress.yaml