apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- sealed-secrets.yaml
namespace: dev
patchesStrategicMerge:
- patch-deployment.yaml
- patch-ingress.yaml
images:
- name: ghcr.io/verde-websites/fpl-infra/myfpl-api
  digest: sha256:47d4c8bf28f0d2d8c4a8ec98fca8a7087b2d320bf7480e33e9c3f5d51df932ae
