apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- sealed-secrets.yaml
namespace: dev
patchesStrategicMerge:
- patch-deployment.yaml
- patch-ingress.yaml
images:
- name: ghcr.io/verde-websites/fpl-infra/myfpl-api
  digest: sha256:b9e3b57835885970432d468b858c08d272e70c629591159240c72ba84205e605
