---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager
  namespace: network
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgAFYHloJSErWuoYmWP/NTxqwmexZKIO79gxixQcKJn7XRc+APeJuZ2Zy/XSt3Nxg1ma/vzS5bePrqTydBnKMfOGONQkV4FULI14PO+O7AIVppImNXDPLtUEe4Rq7GAXtt9zLalzMiGqJtoIFY1lU2WGSysM15v+6YTg6vAIhseFDvt2jdrjCz6GAvTAzhEFwrpxoOD86z0giMxQvMv3VdXEdJHQyD23CotlTs0GC8wh1c8C7CbGusV69v5CRDzJ374KgnTAtIq1SQUCl4tuVd4LoZ0q4UnaLwvpMftp+VSDSyWTZMStvej+qu92iUWursc0tw7WODRtsG9bFSSAcsZwrSPrby+QyHTiFz1TKcLJjCMwTd3lQBPEkATsDme1uiiVxpd7NP1/Uw5nTlsHHiKT47ftZiRoThRhhkkfobI33ooLi61IWd4wGOYFDtbpvv4gwvE/UImkSO09/aCL6AJRTcdgp8xWVnD5T6K5es8aMwOPx8K6Si4+joPQ+0FnLNzoCa4TgVB2czPBbwuW0CY+qpRJM5LSRD/FUNAnDWPjI+beR4XNI/0/hzZMw6CO47w1qBwdVE8+/GsoX+ABsZSBhER2PnHNfHYLprukS5555w2WPcf0voWKVetx0DyDid7Y8bgHHcNCSI37rlCh9BKHM3qhCIgn9lzIK47g+dDgHVL8EOStoVGlbiQ+6laJ7kIA8FcmiVsqodRwAcequMcV8+o6nOKTMd/PNEzSw4VSMBANJFXjq6uc
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager
      namespace: network