apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: ops
data:
  registries.conf: |
    registries:
      - name: ghcr
        prefix: ghcr.io
        api_url: https://ghcr.io
        credentials: pullsecret:ops/github-repo-secret

