---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-url
  namespace: apps
spec:
  encryptedData:
    databaseDsn: AgAThoi9eNzPthcs2AC69IL8Gfy8XgeBjswEJD+7bnvPfmjEnycoLxlhoS50N0dejK5s8a8q2o6+rWjZWt/bGQOFxBKMpg6Sp3NOLQ9hUuG5DuC5CcUmPvgqafNiiAxaAcnOiQENq9wxjeF5lfCcGpOHYhskrORZBSFXpi0u3Z63g7XYFdllGcw3LRirEZIEjc87d/fizPa0eoXYtD1Qtd2oR1fobyQVNBgBNBGgVAJK9AO6VV+t1dMOTuljOx2oHUmLpxhroVRubivjGn4HqDuBlLQm/RxBw67P7Je4mwf+86OnURUY1trIf2/VO480Lz1V+88k+ZptuNzD2T6jrh9Oi9iUQWMId8Kzijd5cgMkF4WMW3fE15izdX/miN/iRm9hCIiuoFn7FqVylKCfPOrqFZpkGYLlSDkXCCF9jInzFrm0Tr0zYnbQN24hPMnPZ6WehMs3PBLzooCrt7pVHjeynSD53tkhk3Ym2kXKCdhUYDcqoVx0KROcDRfgg+UT+uizgtsTIi2A8MSuSXoehYTm8gWi/wfqtu+v9FnUawb1ONKJNSlg6iBm3zqc3Nka2QhD1Jyx/A5ze+60YPmLDTXDgiLeagiITlo2RToh4tDXaa6vikw0X+QkvskCQqHBDMSYWiURao46QHM9O/UK3MCR8YpKa3odHLRH3P0eMNLJqE9oOzvfox9SlwbhG7GlIpiVDNwIq/EH7nv20izGM/SK2yKWo7ghbHqCVh7CMLqQ+J4CzJz9zdk3e3+pGDveq9oWoxEdRrQ8cK3dN/qiKGO5fS39mPIEfJb7+HCIZMmmxr3S1v7q/uzQGf2oNw==
  template:
    metadata:
      creationTimestamp: null
      name: db-url
      namespace: apps
