---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager
  namespace: network
spec:
  encryptedData:
    CLOUDFLARE_TOKEN: AgCK2YW94KiaUrhE8oyz/7l2nHZSUXIQMldju0lIGyazQC1noI+71ZeP1G+pc8OmgQGC9RGusI6W7Y8BFtSC3VA9YY3ZJ4LaDMlt/KpqmL7su2HpuB9Ql44zDif/o3oHpiEUJPd3Hbqj/njcyVSZwHaIW17xEZg5z0kHuLfx6K5h2EzAnzAkO1JVRZvzJKeBswwBSk9HJgy2tbq800LMDAmKaRv2WCgXaQlQl3Vshy83W1Bvb863MfETYY/8pi7IzZ0b54vAjWNA/HQhjRLcKE30By8teJr6AGvi6/0515iBzT0IX+RZ7snZRmtGDSVaPV3SMfnqFY8vmIDRnAYBJnEHoQ5TWt35UJkLkW0zPLaKMgHKR0jm1/Md6oSpebDd9rZW6kvx80Gzl/ZgRciOEm5Vxbg2G29jAeI/aJ6Silmk8Bbt3+OyljSMwbbK5ltN6OSAXNM202CUglXkxhIb3T7QbYmkdSvqE7+myZO3Icw7iGo2E0zaElsZdc2ip1GWjYnxugDcjzqPyxc93R1hEYcFyyof838Kw25x4qmcM9V28vMqo88ZauRKbTs2RUG8Cx3UUJKRFQsZ1QMzgaQjHtjsKOHgyHI5dPR5e0MuhZDF7gVeU33WG8awFc+zPuiZouFAEkazSQ/vb9rKYvyKGs11fj3nlBSrX/n3qs8UVhzwoUpg5prLY79MCieODsllvpgy39nggd01GS9E0jwnGYAc/2P3T+59h7TiSlOMEEy+GE3csP0hK26H
  template:
    metadata:
      creationTimestamp: null
      name: cert-manager
      namespace: network
