
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: reflector
    version: 7.1.288
    releaseName: reflector
    repo: https://emberstack.github.io/helm-charts
    valuesFile: values.yaml
    namespace: ops