apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - repo: https://charts.jetstack.io
    name: cert-manager
    version: v1.15.3
    includeCRDs: true
    releaseName: cert-manager
    valuesFile: helm-values.yaml
    namespace: network

resources:
  #- https://github.com/cert-manager/cert-manager/releases/download/v1.15.3/cert-manager.crds.yaml
  - resources/clusterissuer.yaml
  - resources/sealed-secrets.yaml
