---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  acme:
    email: admin@atlanticsites.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-key
    solvers:
    - dns01:
        cloudflare:
          email: admin@atlanticsites.com
          apiTokenSecretRef:
            name: cloudflare-api-key
            key: api-key
