apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    version: 1.15.3
    namespace: cert-manager
    includeCRDs: true
    valuesInline:
      crds:
        enabled: true
      global:
        leaderElection:
          namespace: cert-manager

resources:
  # - namespace.yaml
  - cluster-issuers.yaml